version: '3.7'
services:
  apache_php:
    build:
       context: apache
    image: monllar_apache
    container_name: monllar_apache
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ${RUTA_CODIGO_FUENTE}:/var/www/html/
      - ./apache/conf/monllar.ini:/usr/local/etc/php/conf.d/monllar.ini
      - ./apache/conf/monllar.conf:/etc/apache2/sites-available/monllar.conf
      - monllar_html_src:/tmp
    depends_on:
      - mysql
    networks:
      - monllar
  mysql: 
    build:
       context: mysql
    image: monllar_mysql
    container_name: monllar_mysql
    env_file: .env
    ports:
      - 3306:3306
    volumes:
     - ./mysql/lib/:/var/lib/mysql
     - ./mysql/conf/monllar.cnf:/etc/mysql/conf.d/monllar.cnf
     - monllar_html_src:/tmp
    environment:
      # defaul administator user is root
      MYSQL_USER: ${MONLLAR_MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MONLLAR_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MONLLAR_MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MONLLAR_MYSQL_PASSWORD}
    networks: 
      - monllar
  
  sonarqube:
    build:
      context: sonarqube
    image: sonarqube
    container_name: monllar_sonarqube
    env_file: .env
    ports:
      - 7000:9000
    volumes:
      - ./sonarqube/conf/sonar.properties:/opt/sonarqube/conf/sonar.properties
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      # - ./sonarqube/extensions:/opt/sonarqube/extensions
    networks: 
      - monllar

  sonarqube_mysql: 
    image: mysql:5.6
    container_name: sonarqube_mysql
    env_file: .env
    ports:
      - 3307:3306
    volumes:
      - ${RUTA_CODIGO_FUENTE}:/var/www/html/
    environment:
      # defaul administator user is root
      MYSQL_USER: ${SONARQUBE_MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${SONARQUBE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SONARQUBE_MYSQL_DATABASE}
      MYSQL_PASSWORD: ${SONARQUBE_MYSQL_PASSWORD}
    networks: 
      - monllar
    
networks:
  monllar:
    driver: bridge

volumes:
  monllar_html_src: