version: '3.7'
services:
  apache_php:
    build:
       context: apache
    image: monllar_apache
    container_name: monllar_apache
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ${RUTA_CODIGO_FUENTE}:/var/www/html/
      - ./apache/conf/monllar.ini:/usr/local/etc/php/conf.d/monllar.ini
      - ./apache/conf/monllar.conf:/etc/apache2/sites-available/monllar.conf
    depends_on:
      - mysql
    networks:
      - monllar
  mysql: 
    build:
       context: mysql
    image: monllar_mysql
    container_name: monllar_mysql
    env_file: .env
    ports:
      - 3306:3306
    volumes:
     - ./mysql/lib/:/var/lib/mysql
     - ./mysql/conf/monllar.cnf:/etc/mysql/conf.d/monllar.cnf
    environment:
      # defaul administator user is root
      MYSQL_USER: ${MONLLAR_MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MONLLAR_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MONLLAR_MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MONLLAR_MYSQL_PASSWORD}
    networks: 
      - monllar
    
networks:
  monllar:
    driver: bridge