version: '3'
services:
  apache_php:
    build:
       context: .
       dockerfile: Dockerfile-php
    container_name: monllar_apache_php
    ports:
      - 80:80
    volumes:
      - ../../:/var/www/html/
      - ./conf-apache/custom_php.ini:/etc/php/7.1/apache2/conf.d/custom_php.ini
      - ./conf-apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
    links:
      - mysql
  mysql: 
    build:
       context: .
       dockerfile: Dockerfile-percona
    container_name: monllar_db_mysql
    ports:
      - 6666:3306
    volumes:
     - ./mysql/lib/:/var/lib/mysql
    environment:
      # defaul administator user is root
      MYSQL_USER: monllar
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monllar
      MYSQL_PASSWORD: monllar
    
